baseurl: /
languageCode: en-us
title: KJ's career development blog site
theme: hugo-lithium
googleAnalytics: ''
disqusShortname: ''
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
permalinks:
  post: /:year/:month/:day/:slug/
menu:
  main:
    - name: About
      url: /about/
    - name: GitHub
      url: https://github.com/kljohnson4good/Blog
    - name: Linked-In
      url: https://www.linkedin.com/in/kristi-johnson-b315a9157/
    - name: Tips-n-Tricks
      url: /tips-n-tricks/
params:
  MathJaxCDN: //cdnjs.cloudflare.com/ajax/libs
  MathJaxVersion: 2.7.5
  description: A website built through Hugo and blogdown.
  favicon: me.png
  highlightjsCDN: //cdnjs.cloudflare.com/ajax/libs
  highlightjsLang:
    - r
    - yaml
  highlightjsTheme: github
  highlightjsVersion: 9.12.0
  logo:
    alt: Logo
    height: 40
    url: logo-home-png-7411.png
    width: 40
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: yes

